api:
  api_id: '123456'
  api_hash: 'your_api_hash'
  bot_token: 'bot:token'

mono_token: 'mono_token'

whitelist:
  - your_username

visible_accounts:
  - iban: UA123455432324235432523423
    alias: 'Alias'
  - iban: UA123456789123456789012345
